import os
from backend.app.core.config import DATA_DIR

def ensure_data_dir():
    """Ensures the data and logs directories exist."""
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs("logs", exist_ok=True)

def log_interaction(query, response, model_type, is_gold=False):
    """Logs an interaction for future fine-tuning."""
    import json
    import datetime
    log_entry = {
        "timestamp": datetime.datetime.now().isoformat(),
        "query": query,
        "response": response,
        "model": model_type,
        "is_gold": is_gold # True if generated by 70B (either directly or via escalation)
    }
    with open("logs/interactions.jsonl", "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")
